#! /bin/sh

sxhkd &

bspc monitor -d web dev files media

bspc config pointer_modifier control
bspc config pointer_action1 resize_corner

bspc config normal_border_color "#152233"
bspc config border_width         2
bspc config window_gap          12

bspc config click_to_focus any
bspc config focus_follows_pointer false

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
